;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Saved/Tolgee/Temp/NobleMetals
DestinationPath=Mods/GameFeatures/NobleMetals/Content/Localization/NobleMetals
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=ja
CulturesToGenerate=zh-Hans
ManifestName=NobleMetals.manifest
ArchiveName=NobleMetals.archive
PortableObjectName=NobleMetals.po

[GatherTextStep0]
CommandletClass=InternationalizationExport
bImportLoc=true
LocalizedTextCollapseMode=ELocalizedTextCollapseMode::IdenticalTextIdAndSource
POFormat=EPortableObjectFormat::Crowdin

