;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/NobleMetals/Content/Localization/NobleMetals
DestinationPath=Mods/GameFeatures/NobleMetals/Content/Localization/NobleMetals
ManifestName=NobleMetals.manifest
ArchiveName=NobleMetals.archive
CulturesToGenerate=en
CulturesToGenerate=ja
CulturesToGenerate=zh-Hans

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationReport
bWordCountReport=true
WordCountReportName=NobleMetals.csv

