;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/NobleMetals/Content/Localization/NobleMetals
DestinationPath=Mods/GameFeatures/NobleMetals/Content/Localization/NobleMetals
ManifestName=NobleMetals.manifest
ArchiveName=NobleMetals.archive
ResourceName=NobleMetals.locres
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateSafeWhitespace=false
bValidateRichTextTags=false
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=ja
CulturesToGenerate=zh-Hans
CulturesToGenerate=de

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationResource

